version: '3.9'

services:
  database:
    restart: always
    image: postgres:16
    container_name: database
    ports:
      - '5445:5432'
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis
    command: redis-server --maxmemory-policy volatile-ttl
    ports:
      - '6379:6379'
    sysctls:
      - net.core.somaxconn=250
    depends_on:
      - database

  celery:
    build:
      context: djangopdfmaker/
      dockerfile: Dockerfile
    container_name: celery
    command: celery -A config.settings worker --loglevel=debug --logfile=log/celery.log
    volumes:
      - ./djangopdfmaker/:/usr/src/app/
    env_file:
      - .env
    depends_on:
      - database
      - redis

  flower:
    build:
      context: djangopdfmaker/
      dockerfile: Dockerfile
    container_name: flower
    command: celery -A config.settings flower
    env_file:
      - .env
    ports:
      - 5555:5555
    depends_on:
      - database
      - redis
      - celery

  server:
    restart: always
    build:
      context: djangopdfmaker/
      dockerfile: Dockerfile
    container_name: djangopdfmaker
    volumes:
      - ./djangopdfmaker/:/usr/src/app/
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - database
      - redis
      - celery
      - flower
    command: >
      sh -c "
      python manage.py migrate  --noinput &&
      python manage.py runserver 0.0.0.0:8000
      "

volumes:
  db-data:
