# Generated by Django 4.2.7 on 2023-11-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generatedpdf",
            name="pdf_file",
            field=models.FileField(upload_to="generated_pdfs/"),
        ),
        migrations.AlterField(
            model_name="task",
            name="html_file",
            field=models.FileField(blank=True, null=True, upload_to="html_files/"),
        ),
    ]
