# Generated by Django 4.2.7 on 2023-11-16 23:40

from django.db import migrations, models
import src.common.utils


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_generatedpdf_pdf_file_alter_task_html_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="html_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=src.common.utils.generate_unique_filename,
            ),
        ),
    ]
