# Generated by Django 4.2.7 on 2023-11-17 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_task_html_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("IN_PROGRESS", "IN PROGRESS"),
                    ("COMPLETED", "COMPLETED"),
                    ("ERROR", "ERROR"),
                ],
                db_index=True,
                default="IN_PROGRESS",
                max_length=20,
            ),
        ),
    ]
