# Generated by Django 4.2.7 on 2023-11-17 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="status_message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
