# Generated by Django 4.2.7 on 2023-11-17 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_task_status_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generatedpdf",
            name="task",
        ),
        migrations.AddField(
            model_name="task",
            name="generatedpdf",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.generatedpdf",
            ),
        ),
    ]
