# Generated by Django 4.2.7 on 2023-11-17 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_generatedpdf_task_task_generatedpdf"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="generatedpdf",
            new_name="generated_pdf",
        ),
    ]
