# Generated by Django 4.2.7 on 2023-11-17 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_rename_generatedpdf_task_generated_pdf"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="html_file",
            new_name="html_source_file",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="url",
            new_name="source_url",
        ),
    ]
