# Generated by Django 4.2.7 on 2023-11-17 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_rename_html_file_task_html_source_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="user",
        ),
    ]
