# Generated by Django 4.2.7 on 2023-11-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_remove_task_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
